version: "3"
services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_DB: rolodex_development
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data
  app:
    build: .
    ports:
      - 8080:8080
    command: ["./wait-for-it.sh", "db:5432", "--", "./main"]
    depends_on:
      - db
volumes:
  data:
    driver: local
